development:
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: rebook_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: rebook_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: rebook_production
  pool: 5
  username: root
  password:
