default_twitter: &default_twitter
  twitter_api_key: 'aHcQFyzV3OmOyHbgcZRqTI31N'
  twitter_api_secret: 'XK1qlwhR6KXCjpv1imkaARraPhpF4uvlkMLRkBRANQEEQbZjr9'

development:
  secret_key_base: 'hogehogehoge'
  <<: *default_twitter

test:
  secret_key_base: 'fogafogafoga'
  <<: *default_twitter

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>